server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/micro_userdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  jwt:
    secret: jkSHs88vnsdfn329dkJsZqPlos82Kz9a
    expiration: 86400000
